Add docs check CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -57,10 +57,39 @@ jobs:
             exit 1
           fi
 
+  docs-check:
+    name: Docs check
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install tools
+        run: |
+          sudo apt-get update -y
+          sudo npm install -g markdown-link-check@^3 markdownlint-cli2@^0 cspell@^8
+
+      - name: Check broken links
+        run: |
+          markdown-link-check -q -c .markdown-link-check.json README.md
+
+      - name: Check typos
+        run: |
+          npx cspell "README.md" --no-progress --no-summary
+          status=$?
+
+          if [ $status -ne 0 ]; then
+            echo "::error::cspell found unknown words. \
+          If a word is correct, add it to .cspell.json under \"words\"."
+
+      - name: Check formatting
+        run: |
+          markdownlint-cli2 README.md
+
   build:
     name: "Build (${{ matrix.name }})"
     runs-on: ${{ matrix.os }}
-    needs: style-check
+    needs: [style-check, docs-check]
     strategy:
       fail-fast: false # Make sure if one build fails, others can still run
       matrix:
@@ -156,7 +185,7 @@ jobs:
   build-sanitize:
     name: "Build (${{ matrix.san }})"
     runs-on: ubuntu-latest
-    needs: style-check
+    needs: [style-check, docs-check]
 
     strategy:
       fail-fast: false
